Repository PixelPack-Games/IDTGA-Game, pull requests merged in 2024-06, with the labels that each got.

#1 setup project
  .vsconfig
  Assets/Scenes.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/AudioManager.asset
  ProjectSettings/ClusterInputManager.asset
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/MemorySettings.asset
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/NetworkManager.asset
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/PresetManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
  ProjectSettings/TimeManager.asset
  ProjectSettings/UnityConnectSettings.asset
  ProjectSettings/VFXManager.asset
  ProjectSettings/VersionControlSettings.asset
  ProjectSettings/XRSettings.asset
Labels: reviewed, setup

#7 Sprites task
  Assets/Sprites.meta
  Assets/Sprites/Enemies.meta
  Assets/Sprites/Enemies/Mimic2.aseprite
  Assets/Sprites/Enemies/Mimic2.aseprite.meta
  Assets/Sprites/Enemies/TestSprite.aseprite
  Assets/Sprites/Enemies/TestSprite.aseprite.meta
  Assets/Sprites/Enemies/WolfGuy.aseprite
  Assets/Sprites/Enemies/WolfGuy.aseprite.meta
  Assets/Sprites/Enemies/basicChest.aseprite
  Assets/Sprites/Enemies/basicChest.aseprite.meta
  Assets/Sprites/Enemies/trainingDummy.aseprite
  Assets/Sprites/Enemies/trainingDummy.aseprite.meta
  Assets/Sprites/Environments.meta
  Assets/Sprites/Environments/GuildHouse-1.aseprite
  Assets/Sprites/Environments/GuildHouse-1.aseprite.meta
  Assets/Sprites/Items.meta
  Assets/Test Scene.unity
  Assets/Test Scene.unity.meta
  ProjectSettings/SceneTemplateSettings.json
Labels: asset, reviewed

#12 linked list and Fighter class
  Assets/ElvGames.meta
  Assets/Scripts/dataStructures.meta
  Assets/Scripts/dataStructures/LinkedList.cs
  Assets/Scripts/dataStructures/LinkedList.cs.meta
  Assets/Scripts/entity/Entity.cs
  Assets/Scripts/entity/Player.meta
  Assets/Scripts/entity/Player/Player.cs
  Assets/Scripts/entity/Player/Player.cs.meta
  Assets/Scripts/entity/Player/classes.meta
  Assets/Scripts/entity/Player/classes/Cleric.cs
  Assets/Scripts/entity/Player/classes/Cleric.cs.meta
  Assets/Scripts/entity/Player/classes/Fighter.cs
  Assets/Scripts/entity/Player/classes/Fighter.cs.meta
  Assets/Scripts/entity/Player/classes/Mage.cs
  Assets/Scripts/entity/Player/classes/Mage.cs.meta
  Assets/Scripts/entity/Player/classes/Rogue.cs
  Assets/Scripts/entity/Player/classes/Rogue.cs.meta
  Assets/Scripts/test/EntityTester.cs
Labels: gameplay, reviewed

#13 data consistency between scenes
  Assets/Scenes/Jerry Test Scene.unity
  Assets/Scenes/test.meta
  Assets/Scenes/test/test.unity
  Assets/Scenes/test/test.unity.meta
  Assets/Scripts/data.meta
  Assets/Scripts/data/DataManager.cs
  Assets/Scripts/data/DataManager.cs.meta
  Assets/Scripts/test/SceneTest.cs
  Assets/Scripts/test/SceneTest.cs.meta
  Assets/prefabs/data.meta
  Assets/prefabs/data/dataManager.prefab
  Assets/prefabs/data/dataManager.prefab.meta
Labels: gameplay, reviewed
