Repository PixelPack-Games/IDTGA-Game, pull requests merged in 2024-07, with the labels that each got.

#24 Read.me
  README.md
Labels: reviewed, setup

#25 NPC Interactions
  Assets/Prefabs/Canvas.prefab
  Assets/Prefabs/Canvas.prefab.meta
  Assets/Prefabs/DialogueBox.prefab
  Assets/Prefabs/DialogueBox.prefab.meta
  Assets/Prefabs/NPCs.meta
  Assets/Prefabs/NPCs/NPC.prefab
  Assets/Prefabs/NPCs/NPC.prefab.meta
  Assets/Prefabs/player/Test Player.prefab
  Assets/Prefabs/player/Test Player.prefab.meta
  Assets/Scenes/Dans_Test_Scene.unity
  Assets/Scenes/NPC_Interaction_Test.unity
  Assets/Scenes/NPC_Interaction_Test.unity.meta
  Assets/Scripts/Interactable.cs
  Assets/Scripts/NPC.meta
  Assets/Scripts/NPC/DisplayDialogue.cs
  Assets/Scripts/NPC/DisplayDialogue.cs.meta
  Assets/Scripts/NPC/NPC_Controller.cs
  Assets/Scripts/NPC/NPC_Controller.cs.meta
  Assets/Scripts/Player.meta
  Assets/Scripts/Player/PlayerMovement.cs
  Assets/Scripts/Player/PlayerMovement.cs.meta
  Assets/Scripts/Player/Player_Interaction_Controller.cs
  Assets/Scripts/Player/Player_Interaction_Controller.cs.meta
  Assets/Scripts/Player/Player_Movement_Only.cs
  Assets/Scripts/Player/Player_Movement_Only.cs.meta
  ProjectSettings/TagManager.asset
Labels: gameplay, UI, reviewed

#22 menu changes to guild scene on button click
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/UI.meta
  Assets/Scripts/UI/MainMenu.cs
  Assets/Scripts/UI/MainMenu.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: menu

#21 simple global multiplayer
  Assets/Scenes/jyj_multiplayerTest.unity
  Assets/Scripts/network/Relay.cs
  Assets/Scripts/network/Relay.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: gameplay

#30 build stuff
  Assets/Inventory System/Scriptable Objects/Inventory/Player Inventory.asset
  Assets/Prefabs/player/Player 2.prefab
  Assets/Scenes/Dans_Test_Scene.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/NPC_Interaction_Test.unity
  Assets/Scripts/FollowerPlayerCam.cs
  Assets/Scripts/network/BattleSystemNetwork.cs
  Assets/Scripts/network/Relay.cs
  Assets/Unity.VisualScripting.Generated/VisualScripting.Core/AotStubs.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: asset, gameplay, UI, menu, setup
